//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliTraxx.PolygonService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="polygonData", Namespace="http://schemas.datacontract.org/2004/07/LATATrax.Models")]
    [System.SerializableAttribute()]
    public partial class polygonData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<IntelliTraxx.PolygonService.LatLon> geoFenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid geoFenceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string geoTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double maxLatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double maxLonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double minLatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double minLonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string notesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string polyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double radiusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<IntelliTraxx.PolygonService.LatLon> geoFence {
            get {
                return this.geoFenceField;
            }
            set {
                if ((object.ReferenceEquals(this.geoFenceField, value) != true)) {
                    this.geoFenceField = value;
                    this.RaisePropertyChanged("geoFence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid geoFenceID {
            get {
                return this.geoFenceIDField;
            }
            set {
                if ((this.geoFenceIDField.Equals(value) != true)) {
                    this.geoFenceIDField = value;
                    this.RaisePropertyChanged("geoFenceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string geoType {
            get {
                return this.geoTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.geoTypeField, value) != true)) {
                    this.geoTypeField = value;
                    this.RaisePropertyChanged("geoType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double maxLat {
            get {
                return this.maxLatField;
            }
            set {
                if ((this.maxLatField.Equals(value) != true)) {
                    this.maxLatField = value;
                    this.RaisePropertyChanged("maxLat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double maxLon {
            get {
                return this.maxLonField;
            }
            set {
                if ((this.maxLonField.Equals(value) != true)) {
                    this.maxLonField = value;
                    this.RaisePropertyChanged("maxLon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double minLat {
            get {
                return this.minLatField;
            }
            set {
                if ((this.minLatField.Equals(value) != true)) {
                    this.minLatField = value;
                    this.RaisePropertyChanged("minLat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double minLon {
            get {
                return this.minLonField;
            }
            set {
                if ((this.minLonField.Equals(value) != true)) {
                    this.minLonField = value;
                    this.RaisePropertyChanged("minLon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                if ((object.ReferenceEquals(this.notesField, value) != true)) {
                    this.notesField = value;
                    this.RaisePropertyChanged("notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string polyName {
            get {
                return this.polyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.polyNameField, value) != true)) {
                    this.polyNameField = value;
                    this.RaisePropertyChanged("polyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double radius {
            get {
                return this.radiusField;
            }
            set {
                if ((this.radiusField.Equals(value) != true)) {
                    this.radiusField = value;
                    this.RaisePropertyChanged("radius");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LatLon", Namespace="http://schemas.datacontract.org/2004/07/LATATrax.Models")]
    [System.SerializableAttribute()]
    public partial class LatLon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Alt {
            get {
                return this.AltField;
            }
            set {
                if ((this.AltField.Equals(value) != true)) {
                    this.AltField = value;
                    this.RaisePropertyChanged("Alt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Lat {
            get {
                return this.LatField;
            }
            set {
                if ((this.LatField.Equals(value) != true)) {
                    this.LatField = value;
                    this.RaisePropertyChanged("Lat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Lon {
            get {
                return this.LonField;
            }
            set {
                if ((this.LonField.Equals(value) != true)) {
                    this.LonField = value;
                    this.RaisePropertyChanged("Lon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PolygonService.IPolygonService")]
    public interface IPolygonService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolygonService/getPolygons", ReplyAction="http://tempuri.org/IPolygonService/getPolygonsResponse")]
        System.Collections.Generic.List<IntelliTraxx.PolygonService.polygonData> getPolygons();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolygonService/getPolygons", ReplyAction="http://tempuri.org/IPolygonService/getPolygonsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<IntelliTraxx.PolygonService.polygonData>> getPolygonsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolygonService/getPolygon", ReplyAction="http://tempuri.org/IPolygonService/getPolygonResponse")]
        IntelliTraxx.PolygonService.polygonData getPolygon(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolygonService/getPolygon", ReplyAction="http://tempuri.org/IPolygonService/getPolygonResponse")]
        System.Threading.Tasks.Task<IntelliTraxx.PolygonService.polygonData> getPolygonAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolygonService/addPolygon", ReplyAction="http://tempuri.org/IPolygonService/addPolygonResponse")]
        string addPolygon(IntelliTraxx.PolygonService.polygonData poly);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolygonService/addPolygon", ReplyAction="http://tempuri.org/IPolygonService/addPolygonResponse")]
        System.Threading.Tasks.Task<string> addPolygonAsync(IntelliTraxx.PolygonService.polygonData poly);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolygonService/deletePolygon", ReplyAction="http://tempuri.org/IPolygonService/deletePolygonResponse")]
        void deletePolygon(System.Guid GeoFenceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolygonService/deletePolygon", ReplyAction="http://tempuri.org/IPolygonService/deletePolygonResponse")]
        System.Threading.Tasks.Task deletePolygonAsync(System.Guid GeoFenceID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPolygonServiceChannel : IntelliTraxx.PolygonService.IPolygonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PolygonServiceClient : System.ServiceModel.ClientBase<IntelliTraxx.PolygonService.IPolygonService>, IntelliTraxx.PolygonService.IPolygonService {
        
        public PolygonServiceClient() {
        }
        
        public PolygonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PolygonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PolygonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PolygonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<IntelliTraxx.PolygonService.polygonData> getPolygons() {
            return base.Channel.getPolygons();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<IntelliTraxx.PolygonService.polygonData>> getPolygonsAsync() {
            return base.Channel.getPolygonsAsync();
        }
        
        public IntelliTraxx.PolygonService.polygonData getPolygon(string id) {
            return base.Channel.getPolygon(id);
        }
        
        public System.Threading.Tasks.Task<IntelliTraxx.PolygonService.polygonData> getPolygonAsync(string id) {
            return base.Channel.getPolygonAsync(id);
        }
        
        public string addPolygon(IntelliTraxx.PolygonService.polygonData poly) {
            return base.Channel.addPolygon(poly);
        }
        
        public System.Threading.Tasks.Task<string> addPolygonAsync(IntelliTraxx.PolygonService.polygonData poly) {
            return base.Channel.addPolygonAsync(poly);
        }
        
        public void deletePolygon(System.Guid GeoFenceID) {
            base.Channel.deletePolygon(GeoFenceID);
        }
        
        public System.Threading.Tasks.Task deletePolygonAsync(System.Guid GeoFenceID) {
            return base.Channel.deletePolygonAsync(GeoFenceID);
        }
    }
}
