//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliTraxx.AlertAdminService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="alertClass", Namespace="http://schemas.datacontract.org/2004/07/LATATrax")]
    [System.SerializableAttribute()]
    public partial class alertClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AlertClassIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlertClassNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AlertClassID {
            get {
                return this.AlertClassIDField;
            }
            set {
                if ((this.AlertClassIDField.Equals(value) != true)) {
                    this.AlertClassIDField = value;
                    this.RaisePropertyChanged("AlertClassID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlertClassName {
            get {
                return this.AlertClassNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AlertClassNameField, value) != true)) {
                    this.AlertClassNameField = value;
                    this.RaisePropertyChanged("AlertClassName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="alertVehicle", Namespace="http://schemas.datacontract.org/2004/07/LATATrax")]
    [System.SerializableAttribute()]
    public partial class alertVehicle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlertActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AlertIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid VehicleIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlertAction {
            get {
                return this.AlertActionField;
            }
            set {
                if ((object.ReferenceEquals(this.AlertActionField, value) != true)) {
                    this.AlertActionField = value;
                    this.RaisePropertyChanged("AlertAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AlertID {
            get {
                return this.AlertIDField;
            }
            set {
                if ((this.AlertIDField.Equals(value) != true)) {
                    this.AlertIDField = value;
                    this.RaisePropertyChanged("AlertID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid VehicleID {
            get {
                return this.VehicleIDField;
            }
            set {
                if ((this.VehicleIDField.Equals(value) != true)) {
                    this.VehicleIDField = value;
                    this.RaisePropertyChanged("VehicleID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="alertGeoFence", Namespace="http://schemas.datacontract.org/2004/07/LATATrax")]
    [System.SerializableAttribute()]
    public partial class alertGeoFence : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AlertIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid GeoFenceIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AlertID {
            get {
                return this.AlertIDField;
            }
            set {
                if ((this.AlertIDField.Equals(value) != true)) {
                    this.AlertIDField = value;
                    this.RaisePropertyChanged("AlertID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GeoFenceID {
            get {
                return this.GeoFenceIDField;
            }
            set {
                if ((this.GeoFenceIDField.Equals(value) != true)) {
                    this.GeoFenceIDField = value;
                    this.RaisePropertyChanged("GeoFenceID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dbAlert", Namespace="http://schemas.datacontract.org/2004/07/LATATrax")]
    [System.SerializableAttribute()]
    public partial class dbAlert : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AlertActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AlertClassIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlertClassNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AlertEndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlertFriendlyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AlertIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AlertStartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlertTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string minValField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AlertActive {
            get {
                return this.AlertActiveField;
            }
            set {
                if ((this.AlertActiveField.Equals(value) != true)) {
                    this.AlertActiveField = value;
                    this.RaisePropertyChanged("AlertActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AlertClassID {
            get {
                return this.AlertClassIDField;
            }
            set {
                if ((this.AlertClassIDField.Equals(value) != true)) {
                    this.AlertClassIDField = value;
                    this.RaisePropertyChanged("AlertClassID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlertClassName {
            get {
                return this.AlertClassNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AlertClassNameField, value) != true)) {
                    this.AlertClassNameField = value;
                    this.RaisePropertyChanged("AlertClassName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AlertEndTime {
            get {
                return this.AlertEndTimeField;
            }
            set {
                if ((this.AlertEndTimeField.Equals(value) != true)) {
                    this.AlertEndTimeField = value;
                    this.RaisePropertyChanged("AlertEndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlertFriendlyName {
            get {
                return this.AlertFriendlyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AlertFriendlyNameField, value) != true)) {
                    this.AlertFriendlyNameField = value;
                    this.RaisePropertyChanged("AlertFriendlyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AlertID {
            get {
                return this.AlertIDField;
            }
            set {
                if ((this.AlertIDField.Equals(value) != true)) {
                    this.AlertIDField = value;
                    this.RaisePropertyChanged("AlertID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AlertStartTime {
            get {
                return this.AlertStartTimeField;
            }
            set {
                if ((this.AlertStartTimeField.Equals(value) != true)) {
                    this.AlertStartTimeField = value;
                    this.RaisePropertyChanged("AlertStartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlertType {
            get {
                return this.AlertTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AlertTypeField, value) != true)) {
                    this.AlertTypeField = value;
                    this.RaisePropertyChanged("AlertType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string minVal {
            get {
                return this.minValField;
            }
            set {
                if ((object.ReferenceEquals(this.minValField, value) != true)) {
                    this.minValField = value;
                    this.RaisePropertyChanged("minVal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="linkVehicle", Namespace="http://schemas.datacontract.org/2004/07/LATATrax")]
    [System.SerializableAttribute()]
    public partial class linkVehicle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vehicleIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vehicleID {
            get {
                return this.vehicleIDField;
            }
            set {
                if ((object.ReferenceEquals(this.vehicleIDField, value) != true)) {
                    this.vehicleIDField = value;
                    this.RaisePropertyChanged("vehicleID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="polyData", Namespace="http://schemas.datacontract.org/2004/07/LATATrax")]
    [System.SerializableAttribute()]
    public partial class polyData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid polyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string polyNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid polyID {
            get {
                return this.polyIDField;
            }
            set {
                if ((this.polyIDField.Equals(value) != true)) {
                    this.polyIDField = value;
                    this.RaisePropertyChanged("polyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string polyName {
            get {
                return this.polyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.polyNameField, value) != true)) {
                    this.polyNameField = value;
                    this.RaisePropertyChanged("polyName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="alertData", Namespace="http://schemas.datacontract.org/2004/07/LATATrax")]
    [System.SerializableAttribute()]
    public partial class alertData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntelliTraxx.AlertAdminService.dbAlert alertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<IntelliTraxx.AlertAdminService.alertGeoFence> alertGeoFencesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<IntelliTraxx.AlertAdminService.alertVehicle> alertVehiclesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IntelliTraxx.AlertAdminService.dbAlert alert {
            get {
                return this.alertField;
            }
            set {
                if ((object.ReferenceEquals(this.alertField, value) != true)) {
                    this.alertField = value;
                    this.RaisePropertyChanged("alert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<IntelliTraxx.AlertAdminService.alertGeoFence> alertGeoFences {
            get {
                return this.alertGeoFencesField;
            }
            set {
                if ((object.ReferenceEquals(this.alertGeoFencesField, value) != true)) {
                    this.alertGeoFencesField = value;
                    this.RaisePropertyChanged("alertGeoFences");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<IntelliTraxx.AlertAdminService.alertVehicle> alertVehicles {
            get {
                return this.alertVehiclesField;
            }
            set {
                if ((object.ReferenceEquals(this.alertVehiclesField, value) != true)) {
                    this.alertVehiclesField = value;
                    this.RaisePropertyChanged("alertVehicles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="schedule", Namespace="http://schemas.datacontract.org/2004/07/LATATrax")]
    [System.SerializableAttribute()]
    public partial class schedule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DOWField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EffDtEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EffDtStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid companyidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string createdByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime createdOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime endTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime modifiedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid scheduleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string scheduleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime startTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DOW {
            get {
                return this.DOWField;
            }
            set {
                if ((this.DOWField.Equals(value) != true)) {
                    this.DOWField = value;
                    this.RaisePropertyChanged("DOW");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EffDtEnd {
            get {
                return this.EffDtEndField;
            }
            set {
                if ((this.EffDtEndField.Equals(value) != true)) {
                    this.EffDtEndField = value;
                    this.RaisePropertyChanged("EffDtEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EffDtStart {
            get {
                return this.EffDtStartField;
            }
            set {
                if ((this.EffDtStartField.Equals(value) != true)) {
                    this.EffDtStartField = value;
                    this.RaisePropertyChanged("EffDtStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool active {
            get {
                return this.activeField;
            }
            set {
                if ((this.activeField.Equals(value) != true)) {
                    this.activeField = value;
                    this.RaisePropertyChanged("active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid companyid {
            get {
                return this.companyidField;
            }
            set {
                if ((this.companyidField.Equals(value) != true)) {
                    this.companyidField = value;
                    this.RaisePropertyChanged("companyid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string createdBy {
            get {
                return this.createdByField;
            }
            set {
                if ((object.ReferenceEquals(this.createdByField, value) != true)) {
                    this.createdByField = value;
                    this.RaisePropertyChanged("createdBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime createdOn {
            get {
                return this.createdOnField;
            }
            set {
                if ((this.createdOnField.Equals(value) != true)) {
                    this.createdOnField = value;
                    this.RaisePropertyChanged("createdOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime endTime {
            get {
                return this.endTimeField;
            }
            set {
                if ((this.endTimeField.Equals(value) != true)) {
                    this.endTimeField = value;
                    this.RaisePropertyChanged("endTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string modifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.modifiedByField, value) != true)) {
                    this.modifiedByField = value;
                    this.RaisePropertyChanged("modifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime modifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                if ((this.modifiedOnField.Equals(value) != true)) {
                    this.modifiedOnField = value;
                    this.RaisePropertyChanged("modifiedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid scheduleID {
            get {
                return this.scheduleIDField;
            }
            set {
                if ((this.scheduleIDField.Equals(value) != true)) {
                    this.scheduleIDField = value;
                    this.RaisePropertyChanged("scheduleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string scheduleName {
            get {
                return this.scheduleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.scheduleNameField, value) != true)) {
                    this.scheduleNameField = value;
                    this.RaisePropertyChanged("scheduleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime startTime {
            get {
                return this.startTimeField;
            }
            set {
                if ((this.startTimeField.Equals(value) != true)) {
                    this.startTimeField = value;
                    this.RaisePropertyChanged("startTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vsLink", Namespace="http://schemas.datacontract.org/2004/07/LATATrax")]
    [System.SerializableAttribute()]
    public partial class vsLink : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime endTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string scheduleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime startTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid vIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vehicleIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime endTime {
            get {
                return this.endTimeField;
            }
            set {
                if ((this.endTimeField.Equals(value) != true)) {
                    this.endTimeField = value;
                    this.RaisePropertyChanged("endTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string scheduleName {
            get {
                return this.scheduleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.scheduleNameField, value) != true)) {
                    this.scheduleNameField = value;
                    this.RaisePropertyChanged("scheduleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime startTime {
            get {
                return this.startTimeField;
            }
            set {
                if ((this.startTimeField.Equals(value) != true)) {
                    this.startTimeField = value;
                    this.RaisePropertyChanged("startTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid vID {
            get {
                return this.vIDField;
            }
            set {
                if ((this.vIDField.Equals(value) != true)) {
                    this.vIDField = value;
                    this.RaisePropertyChanged("vID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vehicleID {
            get {
                return this.vehicleIDField;
            }
            set {
                if ((object.ReferenceEquals(this.vehicleIDField, value) != true)) {
                    this.vehicleIDField = value;
                    this.RaisePropertyChanged("vehicleID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlertAdminService.IAlertAdminSvc")]
    public interface IAlertAdminSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/getAlertClasses", ReplyAction="http://tempuri.org/IAlertAdminSvc/getAlertClassesResponse")]
        System.Collections.Generic.List<IntelliTraxx.AlertAdminService.alertClass> getAlertClasses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/getAlertClasses", ReplyAction="http://tempuri.org/IAlertAdminSvc/getAlertClassesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<IntelliTraxx.AlertAdminService.alertClass>> getAlertClassesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/getAlertVehicles", ReplyAction="http://tempuri.org/IAlertAdminSvc/getAlertVehiclesResponse")]
        System.Collections.Generic.List<IntelliTraxx.AlertAdminService.alertVehicle> getAlertVehicles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/getAlertVehicles", ReplyAction="http://tempuri.org/IAlertAdminSvc/getAlertVehiclesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<IntelliTraxx.AlertAdminService.alertVehicle>> getAlertVehiclesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/getAlertGeoFences", ReplyAction="http://tempuri.org/IAlertAdminSvc/getAlertGeoFencesResponse")]
        System.Collections.Generic.List<IntelliTraxx.AlertAdminService.alertGeoFence> getAlertGeoFences();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/getAlertGeoFences", ReplyAction="http://tempuri.org/IAlertAdminSvc/getAlertGeoFencesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<IntelliTraxx.AlertAdminService.alertGeoFence>> getAlertGeoFencesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/getAlerts", ReplyAction="http://tempuri.org/IAlertAdminSvc/getAlertsResponse")]
        System.Collections.Generic.List<IntelliTraxx.AlertAdminService.dbAlert> getAlerts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/getAlerts", ReplyAction="http://tempuri.org/IAlertAdminSvc/getAlertsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<IntelliTraxx.AlertAdminService.dbAlert>> getAlertsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/getAllLinkVehicles", ReplyAction="http://tempuri.org/IAlertAdminSvc/getAllLinkVehiclesResponse")]
        System.Collections.Generic.List<IntelliTraxx.AlertAdminService.linkVehicle> getAllLinkVehicles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/getAllLinkVehicles", ReplyAction="http://tempuri.org/IAlertAdminSvc/getAllLinkVehiclesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<IntelliTraxx.AlertAdminService.linkVehicle>> getAllLinkVehiclesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/getPolygons", ReplyAction="http://tempuri.org/IAlertAdminSvc/getPolygonsResponse")]
        System.Collections.Generic.List<IntelliTraxx.AlertAdminService.polyData> getPolygons();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/getPolygons", ReplyAction="http://tempuri.org/IAlertAdminSvc/getPolygonsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<IntelliTraxx.AlertAdminService.polyData>> getPolygonsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/getLinkedAlertsVehicles", ReplyAction="http://tempuri.org/IAlertAdminSvc/getLinkedAlertsVehiclesResponse")]
        System.Collections.Generic.List<string> getLinkedAlertsVehicles(string alertFriendlyName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/getLinkedAlertsVehicles", ReplyAction="http://tempuri.org/IAlertAdminSvc/getLinkedAlertsVehiclesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> getLinkedAlertsVehiclesAsync(string alertFriendlyName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/getLinkedAlertsGeoFences", ReplyAction="http://tempuri.org/IAlertAdminSvc/getLinkedAlertsGeoFencesResponse")]
        System.Collections.Generic.List<string> getLinkedAlertsGeoFences(string alertFriendlyName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/getLinkedAlertsGeoFences", ReplyAction="http://tempuri.org/IAlertAdminSvc/getLinkedAlertsGeoFencesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> getLinkedAlertsGeoFencesAsync(string alertFriendlyName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/getAlertData", ReplyAction="http://tempuri.org/IAlertAdminSvc/getAlertDataResponse")]
        IntelliTraxx.AlertAdminService.alertData getAlertData(System.Guid alertID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/getAlertData", ReplyAction="http://tempuri.org/IAlertAdminSvc/getAlertDataResponse")]
        System.Threading.Tasks.Task<IntelliTraxx.AlertAdminService.alertData> getAlertDataAsync(System.Guid alertID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/getAllSchedules", ReplyAction="http://tempuri.org/IAlertAdminSvc/getAllSchedulesResponse")]
        System.Collections.Generic.List<IntelliTraxx.AlertAdminService.schedule> getAllSchedules();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/getAllSchedules", ReplyAction="http://tempuri.org/IAlertAdminSvc/getAllSchedulesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<IntelliTraxx.AlertAdminService.schedule>> getAllSchedulesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/getAllSchedulesByVehicle", ReplyAction="http://tempuri.org/IAlertAdminSvc/getAllSchedulesByVehicleResponse")]
        System.Collections.Generic.List<IntelliTraxx.AlertAdminService.vsLink> getAllSchedulesByVehicle(string VehicleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/getAllSchedulesByVehicle", ReplyAction="http://tempuri.org/IAlertAdminSvc/getAllSchedulesByVehicleResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<IntelliTraxx.AlertAdminService.vsLink>> getAllSchedulesByVehicleAsync(string VehicleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/getAllVehiclesBySchedule", ReplyAction="http://tempuri.org/IAlertAdminSvc/getAllVehiclesByScheduleResponse")]
        System.Collections.Generic.List<IntelliTraxx.AlertAdminService.vsLink> getAllVehiclesBySchedule(System.Guid scheduleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/getAllVehiclesBySchedule", ReplyAction="http://tempuri.org/IAlertAdminSvc/getAllVehiclesByScheduleResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<IntelliTraxx.AlertAdminService.vsLink>> getAllVehiclesByScheduleAsync(System.Guid scheduleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/updateAlertData", ReplyAction="http://tempuri.org/IAlertAdminSvc/updateAlertDataResponse")]
        string updateAlertData(IntelliTraxx.AlertAdminService.dbAlert a, System.Collections.Generic.List<IntelliTraxx.AlertAdminService.alertGeoFence> agfList, System.Collections.Generic.List<IntelliTraxx.AlertAdminService.alertVehicle> avList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/updateAlertData", ReplyAction="http://tempuri.org/IAlertAdminSvc/updateAlertDataResponse")]
        System.Threading.Tasks.Task<string> updateAlertDataAsync(IntelliTraxx.AlertAdminService.dbAlert a, System.Collections.Generic.List<IntelliTraxx.AlertAdminService.alertGeoFence> agfList, System.Collections.Generic.List<IntelliTraxx.AlertAdminService.alertVehicle> avList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/deleteAlert", ReplyAction="http://tempuri.org/IAlertAdminSvc/deleteAlertResponse")]
        string deleteAlert(IntelliTraxx.AlertAdminService.dbAlert a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/deleteAlert", ReplyAction="http://tempuri.org/IAlertAdminSvc/deleteAlertResponse")]
        System.Threading.Tasks.Task<string> deleteAlertAsync(IntelliTraxx.AlertAdminService.dbAlert a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/changeAlertStatus", ReplyAction="http://tempuri.org/IAlertAdminSvc/changeAlertStatusResponse")]
        string changeAlertStatus(System.Collections.Generic.List<System.Guid> aList, bool enable, bool updatedb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/changeAlertStatus", ReplyAction="http://tempuri.org/IAlertAdminSvc/changeAlertStatusResponse")]
        System.Threading.Tasks.Task<string> changeAlertStatusAsync(System.Collections.Generic.List<System.Guid> aList, bool enable, bool updatedb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/changeSchedule", ReplyAction="http://tempuri.org/IAlertAdminSvc/changeScheduleResponse")]
        string changeSchedule(string VehicleID, System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/changeSchedule", ReplyAction="http://tempuri.org/IAlertAdminSvc/changeScheduleResponse")]
        System.Threading.Tasks.Task<string> changeScheduleAsync(string VehicleID, System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/deleteSchedules", ReplyAction="http://tempuri.org/IAlertAdminSvc/deleteSchedulesResponse")]
        string deleteSchedules(System.Collections.Generic.List<IntelliTraxx.AlertAdminService.schedule> dSchedules);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/deleteSchedules", ReplyAction="http://tempuri.org/IAlertAdminSvc/deleteSchedulesResponse")]
        System.Threading.Tasks.Task<string> deleteSchedulesAsync(System.Collections.Generic.List<IntelliTraxx.AlertAdminService.schedule> dSchedules);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/deleteSchedulesBySchedule", ReplyAction="http://tempuri.org/IAlertAdminSvc/deleteSchedulesByScheduleResponse")]
        string deleteSchedulesBySchedule(System.Guid scheduleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/deleteSchedulesBySchedule", ReplyAction="http://tempuri.org/IAlertAdminSvc/deleteSchedulesByScheduleResponse")]
        System.Threading.Tasks.Task<string> deleteSchedulesByScheduleAsync(System.Guid scheduleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/deleteSchedulesByVehicle", ReplyAction="http://tempuri.org/IAlertAdminSvc/deleteSchedulesByVehicleResponse")]
        string deleteSchedulesByVehicle(string vehicleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/deleteSchedulesByVehicle", ReplyAction="http://tempuri.org/IAlertAdminSvc/deleteSchedulesByVehicleResponse")]
        System.Threading.Tasks.Task<string> deleteSchedulesByVehicleAsync(string vehicleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/updateSchedules", ReplyAction="http://tempuri.org/IAlertAdminSvc/updateSchedulesResponse")]
        string updateSchedules(System.Collections.Generic.List<IntelliTraxx.AlertAdminService.schedule> sList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/updateSchedules", ReplyAction="http://tempuri.org/IAlertAdminSvc/updateSchedulesResponse")]
        System.Threading.Tasks.Task<string> updateSchedulesAsync(System.Collections.Generic.List<IntelliTraxx.AlertAdminService.schedule> sList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/addVehicleToSchedule", ReplyAction="http://tempuri.org/IAlertAdminSvc/addVehicleToScheduleResponse")]
        string addVehicleToSchedule(System.Guid scheduleID, System.Collections.Generic.List<string> vehicleIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/addVehicleToSchedule", ReplyAction="http://tempuri.org/IAlertAdminSvc/addVehicleToScheduleResponse")]
        System.Threading.Tasks.Task<string> addVehicleToScheduleAsync(System.Guid scheduleID, System.Collections.Generic.List<string> vehicleIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/addSchedulesToVehicle", ReplyAction="http://tempuri.org/IAlertAdminSvc/addSchedulesToVehicleResponse")]
        string addSchedulesToVehicle(string vehicleID, System.Collections.Generic.List<System.Guid> scheduleList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertAdminSvc/addSchedulesToVehicle", ReplyAction="http://tempuri.org/IAlertAdminSvc/addSchedulesToVehicleResponse")]
        System.Threading.Tasks.Task<string> addSchedulesToVehicleAsync(string vehicleID, System.Collections.Generic.List<System.Guid> scheduleList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlertAdminSvcChannel : IntelliTraxx.AlertAdminService.IAlertAdminSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlertAdminSvcClient : System.ServiceModel.ClientBase<IntelliTraxx.AlertAdminService.IAlertAdminSvc>, IntelliTraxx.AlertAdminService.IAlertAdminSvc {
        
        public AlertAdminSvcClient() {
        }
        
        public AlertAdminSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlertAdminSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlertAdminSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlertAdminSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<IntelliTraxx.AlertAdminService.alertClass> getAlertClasses() {
            return base.Channel.getAlertClasses();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<IntelliTraxx.AlertAdminService.alertClass>> getAlertClassesAsync() {
            return base.Channel.getAlertClassesAsync();
        }
        
        public System.Collections.Generic.List<IntelliTraxx.AlertAdminService.alertVehicle> getAlertVehicles() {
            return base.Channel.getAlertVehicles();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<IntelliTraxx.AlertAdminService.alertVehicle>> getAlertVehiclesAsync() {
            return base.Channel.getAlertVehiclesAsync();
        }
        
        public System.Collections.Generic.List<IntelliTraxx.AlertAdminService.alertGeoFence> getAlertGeoFences() {
            return base.Channel.getAlertGeoFences();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<IntelliTraxx.AlertAdminService.alertGeoFence>> getAlertGeoFencesAsync() {
            return base.Channel.getAlertGeoFencesAsync();
        }
        
        public System.Collections.Generic.List<IntelliTraxx.AlertAdminService.dbAlert> getAlerts() {
            return base.Channel.getAlerts();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<IntelliTraxx.AlertAdminService.dbAlert>> getAlertsAsync() {
            return base.Channel.getAlertsAsync();
        }
        
        public System.Collections.Generic.List<IntelliTraxx.AlertAdminService.linkVehicle> getAllLinkVehicles() {
            return base.Channel.getAllLinkVehicles();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<IntelliTraxx.AlertAdminService.linkVehicle>> getAllLinkVehiclesAsync() {
            return base.Channel.getAllLinkVehiclesAsync();
        }
        
        public System.Collections.Generic.List<IntelliTraxx.AlertAdminService.polyData> getPolygons() {
            return base.Channel.getPolygons();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<IntelliTraxx.AlertAdminService.polyData>> getPolygonsAsync() {
            return base.Channel.getPolygonsAsync();
        }
        
        public System.Collections.Generic.List<string> getLinkedAlertsVehicles(string alertFriendlyName) {
            return base.Channel.getLinkedAlertsVehicles(alertFriendlyName);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> getLinkedAlertsVehiclesAsync(string alertFriendlyName) {
            return base.Channel.getLinkedAlertsVehiclesAsync(alertFriendlyName);
        }
        
        public System.Collections.Generic.List<string> getLinkedAlertsGeoFences(string alertFriendlyName) {
            return base.Channel.getLinkedAlertsGeoFences(alertFriendlyName);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> getLinkedAlertsGeoFencesAsync(string alertFriendlyName) {
            return base.Channel.getLinkedAlertsGeoFencesAsync(alertFriendlyName);
        }
        
        public IntelliTraxx.AlertAdminService.alertData getAlertData(System.Guid alertID) {
            return base.Channel.getAlertData(alertID);
        }
        
        public System.Threading.Tasks.Task<IntelliTraxx.AlertAdminService.alertData> getAlertDataAsync(System.Guid alertID) {
            return base.Channel.getAlertDataAsync(alertID);
        }
        
        public System.Collections.Generic.List<IntelliTraxx.AlertAdminService.schedule> getAllSchedules() {
            return base.Channel.getAllSchedules();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<IntelliTraxx.AlertAdminService.schedule>> getAllSchedulesAsync() {
            return base.Channel.getAllSchedulesAsync();
        }
        
        public System.Collections.Generic.List<IntelliTraxx.AlertAdminService.vsLink> getAllSchedulesByVehicle(string VehicleID) {
            return base.Channel.getAllSchedulesByVehicle(VehicleID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<IntelliTraxx.AlertAdminService.vsLink>> getAllSchedulesByVehicleAsync(string VehicleID) {
            return base.Channel.getAllSchedulesByVehicleAsync(VehicleID);
        }
        
        public System.Collections.Generic.List<IntelliTraxx.AlertAdminService.vsLink> getAllVehiclesBySchedule(System.Guid scheduleID) {
            return base.Channel.getAllVehiclesBySchedule(scheduleID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<IntelliTraxx.AlertAdminService.vsLink>> getAllVehiclesByScheduleAsync(System.Guid scheduleID) {
            return base.Channel.getAllVehiclesByScheduleAsync(scheduleID);
        }
        
        public string updateAlertData(IntelliTraxx.AlertAdminService.dbAlert a, System.Collections.Generic.List<IntelliTraxx.AlertAdminService.alertGeoFence> agfList, System.Collections.Generic.List<IntelliTraxx.AlertAdminService.alertVehicle> avList) {
            return base.Channel.updateAlertData(a, agfList, avList);
        }
        
        public System.Threading.Tasks.Task<string> updateAlertDataAsync(IntelliTraxx.AlertAdminService.dbAlert a, System.Collections.Generic.List<IntelliTraxx.AlertAdminService.alertGeoFence> agfList, System.Collections.Generic.List<IntelliTraxx.AlertAdminService.alertVehicle> avList) {
            return base.Channel.updateAlertDataAsync(a, agfList, avList);
        }
        
        public string deleteAlert(IntelliTraxx.AlertAdminService.dbAlert a) {
            return base.Channel.deleteAlert(a);
        }
        
        public System.Threading.Tasks.Task<string> deleteAlertAsync(IntelliTraxx.AlertAdminService.dbAlert a) {
            return base.Channel.deleteAlertAsync(a);
        }
        
        public string changeAlertStatus(System.Collections.Generic.List<System.Guid> aList, bool enable, bool updatedb) {
            return base.Channel.changeAlertStatus(aList, enable, updatedb);
        }
        
        public System.Threading.Tasks.Task<string> changeAlertStatusAsync(System.Collections.Generic.List<System.Guid> aList, bool enable, bool updatedb) {
            return base.Channel.changeAlertStatusAsync(aList, enable, updatedb);
        }
        
        public string changeSchedule(string VehicleID, System.DateTime start, System.DateTime end) {
            return base.Channel.changeSchedule(VehicleID, start, end);
        }
        
        public System.Threading.Tasks.Task<string> changeScheduleAsync(string VehicleID, System.DateTime start, System.DateTime end) {
            return base.Channel.changeScheduleAsync(VehicleID, start, end);
        }
        
        public string deleteSchedules(System.Collections.Generic.List<IntelliTraxx.AlertAdminService.schedule> dSchedules) {
            return base.Channel.deleteSchedules(dSchedules);
        }
        
        public System.Threading.Tasks.Task<string> deleteSchedulesAsync(System.Collections.Generic.List<IntelliTraxx.AlertAdminService.schedule> dSchedules) {
            return base.Channel.deleteSchedulesAsync(dSchedules);
        }
        
        public string deleteSchedulesBySchedule(System.Guid scheduleID) {
            return base.Channel.deleteSchedulesBySchedule(scheduleID);
        }
        
        public System.Threading.Tasks.Task<string> deleteSchedulesByScheduleAsync(System.Guid scheduleID) {
            return base.Channel.deleteSchedulesByScheduleAsync(scheduleID);
        }
        
        public string deleteSchedulesByVehicle(string vehicleID) {
            return base.Channel.deleteSchedulesByVehicle(vehicleID);
        }
        
        public System.Threading.Tasks.Task<string> deleteSchedulesByVehicleAsync(string vehicleID) {
            return base.Channel.deleteSchedulesByVehicleAsync(vehicleID);
        }
        
        public string updateSchedules(System.Collections.Generic.List<IntelliTraxx.AlertAdminService.schedule> sList) {
            return base.Channel.updateSchedules(sList);
        }
        
        public System.Threading.Tasks.Task<string> updateSchedulesAsync(System.Collections.Generic.List<IntelliTraxx.AlertAdminService.schedule> sList) {
            return base.Channel.updateSchedulesAsync(sList);
        }
        
        public string addVehicleToSchedule(System.Guid scheduleID, System.Collections.Generic.List<string> vehicleIDs) {
            return base.Channel.addVehicleToSchedule(scheduleID, vehicleIDs);
        }
        
        public System.Threading.Tasks.Task<string> addVehicleToScheduleAsync(System.Guid scheduleID, System.Collections.Generic.List<string> vehicleIDs) {
            return base.Channel.addVehicleToScheduleAsync(scheduleID, vehicleIDs);
        }
        
        public string addSchedulesToVehicle(string vehicleID, System.Collections.Generic.List<System.Guid> scheduleList) {
            return base.Channel.addSchedulesToVehicle(vehicleID, scheduleList);
        }
        
        public System.Threading.Tasks.Task<string> addSchedulesToVehicleAsync(string vehicleID, System.Collections.Generic.List<System.Guid> scheduleList) {
            return base.Channel.addSchedulesToVehicleAsync(vehicleID, scheduleList);
        }
    }
}
