//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliFleetKeepAlive.IntelliFleetVehicleService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vehicle", Namespace="http://schemas.datacontract.org/2004/07/IntelliFleetService.Models")]
    [System.SerializableAttribute()]
    public partial class Vehicle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehicleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntelliFleetKeepAlive.IntelliFleetVehicleService.alert[] alertsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntelliFleetKeepAlive.IntelliFleetVehicleService.CompanyAlerts[] companyAlertsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntelliFleetKeepAlive.IntelliFleetVehicleService.VehicleExtendedData extendedDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntelliFleetKeepAlive.IntelliFleetVehicleService.GPSData gpsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string insidePolyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isInsideField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime lastMessageReceivedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid runIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehicleID {
            get {
                return this.VehicleIDField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleIDField, value) != true)) {
                    this.VehicleIDField = value;
                    this.RaisePropertyChanged("VehicleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IntelliFleetKeepAlive.IntelliFleetVehicleService.alert[] alerts {
            get {
                return this.alertsField;
            }
            set {
                if ((object.ReferenceEquals(this.alertsField, value) != true)) {
                    this.alertsField = value;
                    this.RaisePropertyChanged("alerts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IntelliFleetKeepAlive.IntelliFleetVehicleService.CompanyAlerts[] companyAlerts {
            get {
                return this.companyAlertsField;
            }
            set {
                if ((object.ReferenceEquals(this.companyAlertsField, value) != true)) {
                    this.companyAlertsField = value;
                    this.RaisePropertyChanged("companyAlerts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IntelliFleetKeepAlive.IntelliFleetVehicleService.VehicleExtendedData extendedData {
            get {
                return this.extendedDataField;
            }
            set {
                if ((object.ReferenceEquals(this.extendedDataField, value) != true)) {
                    this.extendedDataField = value;
                    this.RaisePropertyChanged("extendedData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IntelliFleetKeepAlive.IntelliFleetVehicleService.GPSData gps {
            get {
                return this.gpsField;
            }
            set {
                if ((object.ReferenceEquals(this.gpsField, value) != true)) {
                    this.gpsField = value;
                    this.RaisePropertyChanged("gps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string insidePolyName {
            get {
                return this.insidePolyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.insidePolyNameField, value) != true)) {
                    this.insidePolyNameField = value;
                    this.RaisePropertyChanged("insidePolyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isInside {
            get {
                return this.isInsideField;
            }
            set {
                if ((this.isInsideField.Equals(value) != true)) {
                    this.isInsideField = value;
                    this.RaisePropertyChanged("isInside");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime lastMessageReceived {
            get {
                return this.lastMessageReceivedField;
            }
            set {
                if ((this.lastMessageReceivedField.Equals(value) != true)) {
                    this.lastMessageReceivedField = value;
                    this.RaisePropertyChanged("lastMessageReceived");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid runID {
            get {
                return this.runIDField;
            }
            set {
                if ((this.runIDField.Equals(value) != true)) {
                    this.runIDField = value;
                    this.RaisePropertyChanged("runID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleExtendedData", Namespace="http://schemas.datacontract.org/2004/07/IntelliFleetService")]
    [System.SerializableAttribute()]
    public partial class VehicleExtendedData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehicleFriendlyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehicleModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid companyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string companyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int haulLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string licensePlateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vehicleClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid vehicleClassIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vehicleClassImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vehicleIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Make {
            get {
                return this.MakeField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeField, value) != true)) {
                    this.MakeField = value;
                    this.RaisePropertyChanged("Make");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehicleFriendlyName {
            get {
                return this.VehicleFriendlyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleFriendlyNameField, value) != true)) {
                    this.VehicleFriendlyNameField = value;
                    this.RaisePropertyChanged("VehicleFriendlyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehicleModel {
            get {
                return this.VehicleModelField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleModelField, value) != true)) {
                    this.VehicleModelField = value;
                    this.RaisePropertyChanged("VehicleModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid companyID {
            get {
                return this.companyIDField;
            }
            set {
                if ((this.companyIDField.Equals(value) != true)) {
                    this.companyIDField = value;
                    this.RaisePropertyChanged("companyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string companyName {
            get {
                return this.companyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.companyNameField, value) != true)) {
                    this.companyNameField = value;
                    this.RaisePropertyChanged("companyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int haulLimit {
            get {
                return this.haulLimitField;
            }
            set {
                if ((this.haulLimitField.Equals(value) != true)) {
                    this.haulLimitField = value;
                    this.RaisePropertyChanged("haulLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string licensePlate {
            get {
                return this.licensePlateField;
            }
            set {
                if ((object.ReferenceEquals(this.licensePlateField, value) != true)) {
                    this.licensePlateField = value;
                    this.RaisePropertyChanged("licensePlate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vehicleClass {
            get {
                return this.vehicleClassField;
            }
            set {
                if ((object.ReferenceEquals(this.vehicleClassField, value) != true)) {
                    this.vehicleClassField = value;
                    this.RaisePropertyChanged("vehicleClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid vehicleClassID {
            get {
                return this.vehicleClassIDField;
            }
            set {
                if ((this.vehicleClassIDField.Equals(value) != true)) {
                    this.vehicleClassIDField = value;
                    this.RaisePropertyChanged("vehicleClassID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vehicleClassImage {
            get {
                return this.vehicleClassImageField;
            }
            set {
                if ((object.ReferenceEquals(this.vehicleClassImageField, value) != true)) {
                    this.vehicleClassImageField = value;
                    this.RaisePropertyChanged("vehicleClassImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vehicleID {
            get {
                return this.vehicleIDField;
            }
            set {
                if ((object.ReferenceEquals(this.vehicleIDField, value) != true)) {
                    this.vehicleIDField = value;
                    this.RaisePropertyChanged("vehicleID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GPSData", Namespace="http://schemas.datacontract.org/2004/07/IntelliFleetService.Messages")]
    [System.SerializableAttribute()]
    public partial class GPSData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double latField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double lonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double spdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dir {
            get {
                return this.dirField;
            }
            set {
                if ((this.dirField.Equals(value) != true)) {
                    this.dirField = value;
                    this.RaisePropertyChanged("dir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lat {
            get {
                return this.latField;
            }
            set {
                if ((this.latField.Equals(value) != true)) {
                    this.latField = value;
                    this.RaisePropertyChanged("lat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lon {
            get {
                return this.lonField;
            }
            set {
                if ((this.lonField.Equals(value) != true)) {
                    this.lonField = value;
                    this.RaisePropertyChanged("lon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string messageType {
            get {
                return this.messageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.messageTypeField, value) != true)) {
                    this.messageTypeField = value;
                    this.RaisePropertyChanged("messageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double spd {
            get {
                return this.spdField;
            }
            set {
                if ((this.spdField.Equals(value) != true)) {
                    this.spdField = value;
                    this.RaisePropertyChanged("spd");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="alert", Namespace="http://schemas.datacontract.org/2004/07/IntelliFleetService.Models")]
    [System.SerializableAttribute()]
    public partial class alert : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool alertActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime alertEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid alertIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string alertNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime alertStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int alertTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string latLonEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string latLonStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maxValField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid runIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool alertActive {
            get {
                return this.alertActiveField;
            }
            set {
                if ((this.alertActiveField.Equals(value) != true)) {
                    this.alertActiveField = value;
                    this.RaisePropertyChanged("alertActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime alertEnd {
            get {
                return this.alertEndField;
            }
            set {
                if ((this.alertEndField.Equals(value) != true)) {
                    this.alertEndField = value;
                    this.RaisePropertyChanged("alertEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid alertID {
            get {
                return this.alertIDField;
            }
            set {
                if ((this.alertIDField.Equals(value) != true)) {
                    this.alertIDField = value;
                    this.RaisePropertyChanged("alertID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alertName {
            get {
                return this.alertNameField;
            }
            set {
                if ((object.ReferenceEquals(this.alertNameField, value) != true)) {
                    this.alertNameField = value;
                    this.RaisePropertyChanged("alertName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime alertStart {
            get {
                return this.alertStartField;
            }
            set {
                if ((this.alertStartField.Equals(value) != true)) {
                    this.alertStartField = value;
                    this.RaisePropertyChanged("alertStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int alertType {
            get {
                return this.alertTypeField;
            }
            set {
                if ((this.alertTypeField.Equals(value) != true)) {
                    this.alertTypeField = value;
                    this.RaisePropertyChanged("alertType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string latLonEnd {
            get {
                return this.latLonEndField;
            }
            set {
                if ((object.ReferenceEquals(this.latLonEndField, value) != true)) {
                    this.latLonEndField = value;
                    this.RaisePropertyChanged("latLonEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string latLonStart {
            get {
                return this.latLonStartField;
            }
            set {
                if ((object.ReferenceEquals(this.latLonStartField, value) != true)) {
                    this.latLonStartField = value;
                    this.RaisePropertyChanged("latLonStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maxVal {
            get {
                return this.maxValField;
            }
            set {
                if ((object.ReferenceEquals(this.maxValField, value) != true)) {
                    this.maxValField = value;
                    this.RaisePropertyChanged("maxVal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid runID {
            get {
                return this.runIDField;
            }
            set {
                if ((this.runIDField.Equals(value) != true)) {
                    this.runIDField = value;
                    this.RaisePropertyChanged("runID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompanyAlerts", Namespace="http://schemas.datacontract.org/2004/07/IntelliFleetService")]
    [System.SerializableAttribute()]
    public partial class CompanyAlerts : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AlertIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlertNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AlertID {
            get {
                return this.AlertIDField;
            }
            set {
                if ((this.AlertIDField.Equals(value) != true)) {
                    this.AlertIDField = value;
                    this.RaisePropertyChanged("AlertID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlertName {
            get {
                return this.AlertNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AlertNameField, value) != true)) {
                    this.AlertNameField = value;
                    this.RaisePropertyChanged("AlertName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="systemvar", Namespace="http://schemas.datacontract.org/2004/07/IntelliFleetService")]
    [System.SerializableAttribute()]
    public partial class systemvar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid companyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid varIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string varMaxValField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string varMinValField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string varModByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime varModDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string varNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int varTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid companyID {
            get {
                return this.companyIDField;
            }
            set {
                if ((this.companyIDField.Equals(value) != true)) {
                    this.companyIDField = value;
                    this.RaisePropertyChanged("companyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid varID {
            get {
                return this.varIDField;
            }
            set {
                if ((this.varIDField.Equals(value) != true)) {
                    this.varIDField = value;
                    this.RaisePropertyChanged("varID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string varMaxVal {
            get {
                return this.varMaxValField;
            }
            set {
                if ((object.ReferenceEquals(this.varMaxValField, value) != true)) {
                    this.varMaxValField = value;
                    this.RaisePropertyChanged("varMaxVal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string varMinVal {
            get {
                return this.varMinValField;
            }
            set {
                if ((object.ReferenceEquals(this.varMinValField, value) != true)) {
                    this.varMinValField = value;
                    this.RaisePropertyChanged("varMinVal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string varModBy {
            get {
                return this.varModByField;
            }
            set {
                if ((object.ReferenceEquals(this.varModByField, value) != true)) {
                    this.varModByField = value;
                    this.RaisePropertyChanged("varModBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime varModDate {
            get {
                return this.varModDateField;
            }
            set {
                if ((this.varModDateField.Equals(value) != true)) {
                    this.varModDateField = value;
                    this.RaisePropertyChanged("varModDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string varName {
            get {
                return this.varNameField;
            }
            set {
                if ((object.ReferenceEquals(this.varNameField, value) != true)) {
                    this.varNameField = value;
                    this.RaisePropertyChanged("varName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int varType {
            get {
                return this.varTypeField;
            }
            set {
                if ((this.varTypeField.Equals(value) != true)) {
                    this.varTypeField = value;
                    this.RaisePropertyChanged("varType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IntelliFleetVehicleService.IVehicleService")]
    public interface IVehicleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/getAllVehicles", ReplyAction="http://tempuri.org/IVehicleService/getAllVehiclesResponse")]
        IntelliFleetKeepAlive.IntelliFleetVehicleService.Vehicle[] getAllVehicles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/getAllVehicles", ReplyAction="http://tempuri.org/IVehicleService/getAllVehiclesResponse")]
        System.Threading.Tasks.Task<IntelliFleetKeepAlive.IntelliFleetVehicleService.Vehicle[]> getAllVehiclesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/getVars", ReplyAction="http://tempuri.org/IVehicleService/getVarsResponse")]
        IntelliFleetKeepAlive.IntelliFleetVehicleService.systemvar[] getVars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/getVars", ReplyAction="http://tempuri.org/IVehicleService/getVarsResponse")]
        System.Threading.Tasks.Task<IntelliFleetKeepAlive.IntelliFleetVehicleService.systemvar[]> getVarsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/reloadVars", ReplyAction="http://tempuri.org/IVehicleService/reloadVarsResponse")]
        void reloadVars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/reloadVars", ReplyAction="http://tempuri.org/IVehicleService/reloadVarsResponse")]
        System.Threading.Tasks.Task reloadVarsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVehicleServiceChannel : IntelliFleetKeepAlive.IntelliFleetVehicleService.IVehicleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VehicleServiceClient : System.ServiceModel.ClientBase<IntelliFleetKeepAlive.IntelliFleetVehicleService.IVehicleService>, IntelliFleetKeepAlive.IntelliFleetVehicleService.IVehicleService {
        
        public VehicleServiceClient() {
        }
        
        public VehicleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VehicleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehicleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehicleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IntelliFleetKeepAlive.IntelliFleetVehicleService.Vehicle[] getAllVehicles() {
            return base.Channel.getAllVehicles();
        }
        
        public System.Threading.Tasks.Task<IntelliFleetKeepAlive.IntelliFleetVehicleService.Vehicle[]> getAllVehiclesAsync() {
            return base.Channel.getAllVehiclesAsync();
        }
        
        public IntelliFleetKeepAlive.IntelliFleetVehicleService.systemvar[] getVars() {
            return base.Channel.getVars();
        }
        
        public System.Threading.Tasks.Task<IntelliFleetKeepAlive.IntelliFleetVehicleService.systemvar[]> getVarsAsync() {
            return base.Channel.getVarsAsync();
        }
        
        public void reloadVars() {
            base.Channel.reloadVars();
        }
        
        public System.Threading.Tasks.Task reloadVarsAsync() {
            return base.Channel.reloadVarsAsync();
        }
    }
}
